### ISSUE TITLE
php_threads question

### ISSUE THREAD

**Issue by molchanov1983** [quantuumsnot/botlab#1]
https://github.com/krakjoe/pthreads/issues/613

Hello
I didnot find another way how to reach you
I noticed you have threads issue using php 7.1.0...
Have you solved it? If so could you please help me to solve it too?
Thanks

**Comment by quantuumsnot** [comment]
PHP as a language has so many issues that it is better to work only in single-thread manner. Yes, pthreads work, but for the time I can learn the idea behind them, I managed to be proficient in physics ...

**Comment by quantuumsnot** [comment]
Co-routines, threading and similar shits are no-no ... Stay low and code in C/C++/Go for multicore systems. Or WebWorkers if you don't need a native apps

**Comment by molchanov1983** [comment]
Thanks for your advice
First reason why i would want to have threads because it is cron job that takes hours 
I have 1000 elements (IPv4) in database and for each of them i need to run some function (ping for example) and result i need to store into database 
Using single-thread manner it takes hours that's why i started looking for another solution who to make it faster

**Comment by quantuumsnot** [comment]
One way is to fork for each IP, the other is to use some async lib for that. If I remember right, CURL allows to ping asynchronously. Anyway the most important is to wait for all replies to arrive and be written to an array, so you can then echo that array which holds the results. Oh, and must care how many icmp packets you're sending per second, or ISP/your local firewall can block you.

The most simple forking is to system/exec again your script - `php "name of your script" "your current IP address from the list"`, but it is also a very bad practice
